# Generated by Django 4.0.5 on 2022-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('username', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password1', models.TextField(max_length=10)),
                ('password2', models.TextField(max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
